export const CHANGE_POST = "CHANGE_POST";
export const DELETE_POST = "DELETE_POST";
export const SAVE_NEW_POST = "SAVE_NEW_CARD";

export const LOG_OUT = "LOG_OUT";

export const FETCH_LOGIN_FAIL = "FETCH_LOGIN_FAIL";
export const FETCH_LOGIN_REQUEST = "FETCH_LOGIN_REQUEST";
export const FETCH_LOGIN_SUCCESS = "FETCH_LOGIN_SUCCESS";

export const FETCH_POST_FAIL = "FETCH_POST_FAIL";
export const FETCH_POST_REQUEST = "FETCH_POST_REQUEST";
export const FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS";
