export const CHANGE_POST = "CHANGE_POST";
export const DELETE_POST = "DELETE_POST";
export const SAVE_NEW_POST = "SAVE_NEW_CARD";

export const LOG_IN = "LOG_IN";
export const LOG_OUT = "LOG_OUT";

export const LOGIN_FAIL_REQUEST = "LOGIN_FAIL_REQUEST";
export const LOGIN_QUOTE_REQUEST = "LOGIN_QUOTE_REQUEST";
export const LOGIN_SUCCESS_REQUEST = "LOGIN_SUCCESS_REQUEST";

export const POSTS_FAIL_REQUEST = "POSTS_FAIL_REQUEST";
export const POSTS_QUOTE_REQUEST = "POSTS_QUOTE_REQUEST";
export const POSTS_SUCCESS_REQUEST = "POSTS_SUCCESS_REQUEST";
